### PR TITLE
feat: added error to ForgoComponent

### PR DESCRIPTION
**Pull request by jacob-ebey**
Adding error to ForgoComponent enables things like suspense and error handling that does not break
the whole app tree

Suspense example: https://github.com/jacob-ebey/forgo-ssr-example/tree/suspense

### CODE REVIEW

**Comment by jacob-ebey** [comment]
@jeswin This lays the groundwork for suspense

**Comment by jeswin** [comment]
I'll review this by tomorrow (Monday). Thanks for the PR.

**Comment by jacob-ebey** [comment]
@jeswin I've added a test simple test case and opened a PR to forgo-render-to-string that introduces a hook for handling suspense on the server: https://github.com/jacob-ebey/forgo-render-to-string/pull/1

**Comment by jeswin** [comment]
So as I understand it, here's the capability that the PR adds. It allows a parent component to return a different component if any child (any any level down below) throws an error.

That seems generic (and useful) enough to be in core, but I need to understand where we would use this. Since forgo focuses heavily on being ultra-light weight (2kb gzipped now), we need this to be useful without suspense. Suspense itself cannot be in core [1], but I am totally open to having extension points in core to enable building suspense as an external module. Which is what I suppose you're trying to achieve here.

So, what would be a usecase for this (outside of suspense)?

[1]: Not sure if things have changed, but throw a promise will break the principle of least surprise for most JavaScripters. Persoanlly, I think there were better ways to handle it.

**Comment by jacob-ebey** [comment]
@jeswin This is generic sub component error handling. Suspense is just a single advanced use-case. A simple use-case would be in a micro-frontend architecture where you don't want a single part of the component tree to throw and error and break the rest of the render. You could add a component around each micro-frontend component that could gracefully handle errors. I'll update the test case to demo the basic usage better.

**Comment by jeswin** [comment]
> A simple use-case would be in a micro-frontend architecture where you don't want a single part of the component tree to throw and error and break the rest of the render.

Sold. I'll merge this after completing the review. Thanks.

**Comment by jeswin** [comment]
@jacob-ebey Also, special thanks for patiently explaining what I was missing.

**Pull request merged**
