### PR TITLE
Simplify application code

### PR DESCRIPTION
**Pull request by daychongyang**
A shorter way to mount Forgo Component.

### CODE REVIEW

**Comment by jeswin** [comment]
Method chaining is not consistent with the rest of the API - so that's a problem. I am not averse to the style, just that it doesn't fit into this particular project.

```jsx
createApp(<BasicComponent />).mount('#root');
```

I see the value in createApp(), but there might be people who won't need it. One of the primary goals of forgo is to be absolutely minimal, and we'll have to keep it within the 1000 line budget for now. Your previous change to mount() has already simplified things considerably with the selector string; so my view is that this may not be needed.

This could go into a forgo-tools library. I'll be happy to create one if you think it could help.

**Comment by daychongyang** [comment]
All right!😋

**Comment by jeswin** [comment]
I appreciate the inputs, and I agree with the general usefulness of createApp(). To be more specific about my comment above, I know at least one project in which they load forgo much later - and not during page load.

Thanks.

**Comment by daychongyang** [comment]
OK.

**Pull request closed without merging**
