### PR TITLE
Simplify componentRunner

### PR DESCRIPTION
**Pull request by jeswin**
This PR attempts to simplify the usage of componentRunner().

Benefits:
- removes the need to specify types for exports 
- the name exports can be confusing w.r.t. Node's exports
- Less code

The following code is now simpler:

```tsx
const Component: ForgoComponentCtor<
  ForgoComponentProps &
    ComponentEnvironment<{
      buttonElement: forgo.ForgoRef<HTMLButtonElement>;
      rootElement: forgo.ForgoRef<HTMLDivElement>;
      subrootElement: forgo.ForgoRef<HTMLDivElement>;
      pElement: forgo.ForgoRef<HTMLParagraphElement>;
      remove: () => void;
    }> & { insertionPosition?: "first" | "last" | number }
> = ({ document, exports, insertionPosition }) => {
  // ......
}
```

### CODE REVIEW

**Comment by spiffytech** [comment]
Hmmm... I have mixed feelings.

Pros:

I like that this gets away from the verbose, complex generic arguments. Those are nasty and hard to read. (Although this patch keeps the explicit types, but just moves them out of the generic argument).

Ditching the `Object.assign()` is nice, too.

I definitely like making `run()` take proper JSX syntax. I tried this structure while writing `componentRunner`, not sure why I gave it up. Maybe trouble with types? If it's working I say use it.

Cons: 

This makes the relationship between the component and the calling context implicit instead of explicit; there's no single place to tell how the test interfaces with the component, and anything the component references from outside is scattered throughout its code.

Making `clear()` an explicit and separate step will likely lead to buggy tests, as we'll add closured values that we forget to clear.

---

What about a factory pattern?

```tsx
const myComponentFactory = () => {
    const counter: 1;
    const ref: forgo.ForgoRef<HTMLParagraphElement> = {}
    let update: () => void;

    const MyComponent = () => {
        return {
            render(_props, args) {
                update = args.update;
                return <p ref={ref}>Hello, world!</p>
            }
        }
    }
    return {counter, ref, update, MyComponent}
}

it('does stuff', () => {
  const {data, MyComponent} = myComponentFactory();
  await run(() => <MyComponent />)
});
```

The `return` is a little clunky, and a factory is sorta weird since the component constructor is already a factory, but I think it keeps the best parts of the existing componentRunner and this patch.

Thoughts?

**Comment by jeswin** [comment]
I agree with the downside you listed. Let me see how it can be handled.

One problem with the factory approach (listed below) is w.r.t. non-pointer types:

```tsx
const myComponentFactory = () => {
    const counter: 1;
    // ...
    const MyComponent = () => {
      // ...
    }
    return {counter, ref, update, MyComponent}
}
```

In the example you have, counter is a primitive type. So it's the value of counter that gets captured in the return of the factory method, as opposed to a live reference to it. It can of course be fixed by wrapping it in an object - but let me see if there's a better way to do that.

**Comment by jeswin** [comment]
Implemented the componentFactory() approach you described.

There's no way around wrapping those variables in another; hence we return a "state" which is similar to "exports" we had earlier. One key difference (from the first implementation) however is that the name of this variable (currently "state") can be anything and is declared within the test files, rather than be decided in componentRunner(). 

Does this address your concern?

**Comment by spiffytech** [comment]
Yep! Looks good.

**Comment by jeswin** [comment]
In the tests, I also refrain from destructuring state immediately, since we'll run into the same issues with primitive types.

So we cannot do this (although tempting): 

```tsx
const { Component, state: { buttonElement, someCounter } } = componentFactory();
await run((env) => <Component insertionPosition={2} {...env} />);
```

We could however do this:

```tsx
const { Component, state } = componentFactory();
await run((env) => <Component insertionPosition={2} {...env} />);
const  { buttonElement, someCounter } = state;
```

In the PR, I am not destructuring at all. Just FYI.

**Pull request merged**
