### PR TITLE
#62 incorrect mount timing

### PR DESCRIPTION
**Pull request by spiffytech**
This fixes the issue raised in #62. All tests pass.

@jeswin I'm still a bit fuzzy on how the framework chooses which nodes to store state on. Can you confirm that reordering these calls is safe?

### CODE REVIEW

**Comment by jeswin** [comment]
I think it should be safe.And I agree that it mostly makes sense to call mount after children have mounted - the issue reported is an excellent real world use case. 

However, I agree with your view that syncState and syncProps should be two different functions (instead of syncStateAndProps).

**Comment by jeswin** [comment]
> I'm still a bit fuzzy on how the framework chooses which nodes to store state on.

I'll must explain this better in a README I think. Will be useful.

**Comment by jeswin** [comment]
The only problem I see with the new changes is this: when parent's mount() is called, it won't have childNodes rendered. 
This could be fixed with the suggestion you made - separate the attachProps and mount/unmount logic in syncStateAndProps().

**Comment by spiffytech** [comment]
I've added a test asserting that children have rendered by the time the parent's `mount()` is called, and split up the `mount()` calls from the state/props sync.

**Pull request merged**
