### PR TITLE
feat: expose environment to components

### PR DESCRIPTION
**Pull request by jacob-ebey**
exposing environment to components will allow access to the custom dom for SSR support

### CODE REVIEW

**Comment by jeswin** [comment]
We can certainly do this.

A couple of points/questions.

1. The ForgoEnvType type is not stable - let me explain.

It exposes:

```ts
export type ForgoEnvType = {
  window: Window;
  document: HTMLDocument;
  HTMLElement: typeof HTMLElement;
  Text: typeof Text;
};
```

This list of props seems arbitrary. The reason it had to be done this way is because linkedom did not expose the necessary constructors on window (although it might soon) - so for example window.Text ctor doesn't exist.

If we expose this on ForgoRenderArgs, people are going to depend on it - and it'll break if we ever fix it or clean it up. One option will be to not advertise the 'environment' prop you've added; perhaps call it __environment or something.

2. window seems like a valid candidate to be in ForgoEnvType. Maybe keep the others internal. (Actually, document can be removed since document === window.document).

So maybe to warn users, we can do:

```ts
export type ForgoEnvType = {
  window: Window;
  __internal: {
    HTMLElement: typeof HTMLElement;
    Text: typeof Text;
  }
};
```

3. Should it be passed into the component's ctor instead of the render() method? It doesn't change, and even the ctor can benefit from the env, right?

eg: 
```
export type ForgoCtorArgs = {
  window: Window;
  __internal: {
    HTMLElement: typeof HTMLElement;
    Text: typeof Text;
  }
};

function Component(props: MyProps, args: ForgoCtorArgs) {
  return {
    render(props: MyProps) {
      return <div id="hello">Hello world</div>;
    }
  };
}
```

**Comment by jacob-ebey** [comment]
I like the ctor approach.

**Comment by jeswin** [comment]
I made a small edit to ForgoCtorArgs.

**Comment by jeswin** [comment]
> I like the ctor approach. Maybe we just expose document?

Yeah, so we'll expose document directory as a prop on ForgoEnvType. And the others under __internal - as __internal.Text?

Here's the corresponding linkedom issue: https://github.com/WebReflection/linkedom/issues/16
I think we'll be able to get rid of __internal soon.

**Comment by jeswin** [comment]
Fixed in v.0.0.66. ForgoCtorArgs is available in the component ctor.

**Pull request merged**
